language: python

dist: bionic
sudo: required
cache:
- pip
install:
- sudo apt-get update && sudo apt-get install cookiecutter

script:
- cookiecutter . -v --no-input
  && git clone https://github.com/junegunn/vader.vim vim-plugin/vader.vim
  && ./vim-plugin/test/run-tests.sh
